name: 'lodestar-action'
description: 'Use the Lodestar Cli'
author: LodestarCi
branding:
  icon: git-pull-request
  color: blue
inputs:
  command:
    description: 'lodestar command to run'
    required: true
  git-user:
    description: 'user to authenticate with'
    required: false
  git-token:
    description: 'token to authenticate with'
    required: false
  config-path:
    description: 'path to app config file'
    required: false
  yaml-keys:
    description: 'keys to update when pushing app'
    required: false
  dest-environment:
    description: 'destination environment for push and promote'
    required: false
  src-environment:
    description: 'source environment for promote'
    required: false
  version:
    description: 'the version of lodestar to pull'
    required: false
runs:
  using: 'node12'
  main: "dist/index.js"