name: Test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          git-user: ${{ secrets.GIT_USER }}
          git-token: ${{ secrets.GIT_TOKEN }}
          command: app push
          config-path: test/test-config.yaml
          yaml-keys: tag=1234567
          dest-environment: dev
      - uses: ./
        with:
          git-user: ${{ secrets.GIT_USER }}
          git-token: ${{ secrets.GIT_TOKEN }}
          command: app promote
          config-path: test/test-config.yaml
          src-environment: dev
          dest-environment: qa