name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set SHA
        id: keys
        run: echo "::set-output name=tag::$(git rev-parse --short HEAD)"
      - uses: ./
        with:
          git-user: ${{ secrets.GIT_USER }}
          git-token: ${{ secrets.GIT_TOKEN }}
          command: app push
          config-path: test/test-config.yaml
          yaml-keys: tag=${{ steps.keys.outputs.tag }}
          dest-environment: dev
      - uses: ./
        with:
          git-user: ${{ secrets.GIT_USER }}
          git-token: ${{ secrets.GIT_TOKEN }}
          command: app promote
          config-path: test/test-config.yaml
          src-environment: dev
          dest-environment: qa
      - uses: ./
        with:
          command: install